/*
Saturday, January 12th 2013
init.scd
prm
*/

// creates a Dictionary to store functions for improvisation
~improv = ( );

// creates a dictionary to store the spawning functions for improv
~improvMake= ( );

// creates a dictionary to store Synths in improv
~improvSynth = ( );

// creates a dictionary to store Buses
~improvBus = ( );

// creates a dictionary to store buffers:
~improvBuf = ( );

// creates shared buffers for piece:
