/*
Thursday, November 15th 2012 2012
Load boy Functions.scd
prm
*/

"boy/init.scd".loadRelative;
"boy/mainBell.scd".loadRelative;
"boy/rowFuzz.scd".loadRelative;
"boy/randBell.scd".loadRelative;
"boy/bassline.scd".loadRelative;
"boy/noiseChords.scd".loadRelative;
"boy/trumpet.scd".loadRelative;
"boy/transport.scd".loadRelative;
"boy/endSynth.scd".loadRelative;
"boy/accompSynth.scd".loadRelative;
"boy/endFade.scd".loadRelative;