/*
Thursday, December 13th 2012
loadBoyOhm.scd
prm
*/

"boy/initOhm.scd".loadRelative;
"boy/mainBellOhm.scd".loadRelative;
"boy/rowFuzzOhm.scd".loadRelative;
"boy/randBellOhm.scd".loadRelative;
"boy/basslineOhm.scd".loadRelative;
"boy/noiseChordsOhm.scd".loadRelative;
"boy/trumpetOhm.scd".loadRelative;
"boy/transportOhm.scd".loadRelative;
"boy/endSynthOhm.scd".loadRelative;
"boy/accompSynthOhm.scd".loadRelative;