/*
Wednesday, December 12th 2012
loadConnectionsOhm.scd
prm
*/


"/connections/airSputtersOhm.scd".loadRelative;
"/connections/attackRandomizerOhm.scd".loadRelative;
"/connections/basslinesOhm.scd".loadRelative;
"/connections/cascadeRecordOhm.scd".loadRelative;
"/connections/chordRecordOhm.scd".loadRelative;
"/connections/dronerOhm.scd".loadRelative;
"/connections/granDelayOhm.scd".loadRelative;
"/connections/noteRecordOhm.scd".loadRelative;

